services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}",
        ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 5s

    ports:
      - '5432:5432'

  background-security-check:
    build:
      context: lib
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - '9095:9095'