services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  background-security-check:
    build:
      context: lib
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - '9095:9095'